language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: Paj04kjfVizVNmLe4g18FhOBNWS2NNusLaV525oRlhR5nw5qi2ZVqBLt052CvGP25E0nrzbEPdJlI6PPwuZjpyluf5CrTdMLIo62wXnS5lnlVwCJOL+warqAwsJoTmZbZvcAqxmFIYshE4f0s7xYj8N6+wcJg6v/oOXAQqqdb8WeDw3qr7e8TZLSHIdxEiNzgDhGdKCxyWz+sBDuU87H5iGrsw4zpm8SldzaSiyKC5RHyMgAk4Aar46tFVOatXveQxfx2jwzN6fnyJPv9NhnT+SDTiG+hp3z7msvSH9mEnHSKWSd8QndWZgsXlCCAiH6mGOUTdnKXsPzx/ZO3TOHzIEsg33RErpHxeWs8oEFA/GrTYjDctv7cb6T8rrz/Hh8WNt1+N+0tUW7qIViOwtxWt0yxBGyOVu8EamLowJ9oDtog657do0I85LsmGss+u3N7YNnDG07OBs5W+/FcN45Tqq98JrT1fFocURCOI5uOzrEeHHMDabareHriJ6E4eAvspID4hemAZpZEQEdTwKJoPKw336Zx5QuftMugU8YhtiS6Xol/FvVaXIBPKmdcw3FmqAa/SGf1tQKCpVxVdcW7nToFSAkh0VXrod1LlkszAbkCWcw7PkkioOrTGUTmz/g9Cijl0MtWnNTSiHdTD94wmKQdEARsXNbyxzoA7S1/RU=
